# Generated by Django 4.1.3 on 2023-01-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('female', 'женский'), ('male', 'мужской')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
